apiVersion: v1
kind: Service
metadata:
  name: conscoord-service
  namespace: kgb-conscoord
spec:
  selector:
    app: conscoord-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3086
  type: ClusterIP
