apiVersion: v1
kind: Service
metadata:
  name: conscoord-service
  namespace: kgb-conscoord
spec:
  selector:
    app: conscoord-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
