name: Build and deploy on kubernetes
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, conscoord-client]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          docker build -t garioncox/conscoord-client:${{ github.run_number }} \
          -t garioncox/conscoord-client:latest \
          .

      - name: Push image
        run: |
          docker push garioncox/conscoord-client --all-tags

      - name: Deploy to Kubernetes
        run: |
          export PATH=$PATH:~/.nix-profile/bin:/nix/var/nix/profiles/default/bin
          export IMAGE_TAG=${{ github.run_number }}

          for file in kube/*; do 
              echo "Applying $file"
              cat "$file" | envsubst | kubectl apply -f -; 
          done
