name: Lint on Push
on:
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: [self-hosted, conscoord-client]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t garioncox/conscoord-client:linting
